apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-task-backend
  labels:
    app: ai-task-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-task-backend
  template:
    metadata:
      labels:
        app: ai-task-backend
    spec:
      containers:
        - name: backend
          # The workflow will find this placeholder line and update it on every push
          image: sunil2809/ai-task-backend:de7c878
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            # Add other backend environment variables here (DB connection, secrets, etc.)