apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-task-frontend
  labels:
    app: ai-task-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-task-frontend
  template:
    metadata:
      labels:
        app: ai-task-frontend
    spec:
      containers:
        - name: frontend
          image: sunil2809/ai-task-frontend:b779270
          imagePullPolicy: Always
          ports:
            # --- FIXED TO MATCH YOUR DOCKER FILE INTERNAL PORT ---
            - containerPort: 8080
          volumeMounts:
            - name: cache-volume
              mountPath: /var/cache/nginx
            - name: run-volume
              mountPath: /var/run
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}