apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-task-worker
  labels:
    app: ai-task-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-task-worker
  template:
    metadata:
      labels:
        app: ai-task-worker
    spec:
      containers:
        - name: worker
          # --- FIXED ACCOUNT NAME TO MATCH YOUR DOCKER HUB HASHES ---
          image: sunil2809/ai-task-worker:b6501e1
          imagePullPolicy: Always
          # --- ADDED COMMAND TO FORCE THE QUEUE WORKER TO STAY ALIVE ---
          # (If your script is plain Python and uses an infinite loop instead of Celery, 
          # you can safely delete the 'command' and 'args' lines below)
          command: ["celery"]
          args: ["-A", "worker", "worker", "--loglevel=info"]
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: MONGO_URI
              value: "mongodb+srv://sunilguptait06:Sunil%40mern1@cluster0.stuqq5m.mongodb.net/ai-task-manager?retryWrites=true&w=majority&appName=Cluster0"
            - name: REDIS_URL
              value: "redis://argocd-redis:6379"