apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-task-worker
  labels:
    app: ai-task-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-task-worker
  template:
    metadata:
      labels:
        app: ai-task-worker
    spec:
      containers:
        - name: worker
          image: sunil2809/ai-task-worker:latest
          imagePullPolicy: Always
          # --- REMOVED CELERY OVERRIDE & ADDED STANDBY FORCE LOOP ---
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting worker wrapper..."
              if [ -f "worker.py" ]; then
                python -u worker.py
              else
                echo "worker.py not found in current directory!"
              fi
              echo "Script execution finished. Keeping pod alive for debugging..."
              tail -f /dev/null
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: MONGO_URI
              value: "mongodb+srv://sunilguptait06:Sunil%40mern1@cluster0.stuqq5m.mongodb.net/ai-task-manager?retryWrites=true&w=majority&appName=Cluster0"
            - name: REDIS_URL
              value: "redis://argocd-redis:6379"